app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/dog-show-box.scss, app/controllers/dogs_controller.rb, app/views/dogs/show.html.erb
Added route, action and index
@juagarca @betharms @odealtry please review and merge
=> Dogs show page

app/assets/stylesheets/components/_card-show.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/dogs_controller.rb, app/views/dogs/index.html.erb, app/views/shared/_navbar.html.erb
=> Linksandhovers

Gemfile.lock, app/controllers/dogs_controller.rb, app/views/shared/_navbar.html.erb
=> fixed small bugs

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/edit.html.erb, config/routes.rb, db/migrate/20201118110937_add_columns_to_users.rb, db/migrate/20201118111854_change_bio_column_in_users.rb, db/schema.rb
@juagarca @betharms @odealtry 
Guys I've finished the user update page and added user info to the table. Update method in next pull
=> Edit update user

app/controllers/users_controller.rb, app/views/users/edit.html.erb, config/routes.rb
=> User update and add photo attachment to form

app/controllers/users_controller.rb, app/models/user.rb, app/views/shared/_navbar.html.erb, app/views/users/edit.html.erb, db/schema.rb
=> Avatar in navbar

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card-show.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_dog-index.scss, app/assets/stylesheets/pages/_dog-show.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/dogs_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/dogs/index.html.erb, db/seeds.rb
Hey guys please check and merge
@odealtry @betharms @jtdevuk
=> created map and fixed other minor details

app/assets/stylesheets/components/_flashes.scss, app/assets/stylesheets/components/_index.scss, app/views/shared/_flashes.html.erb
=> finished colour update

app/views/dogs/new.html.erb
=> Form tweaking

app/models/booking.rb, app/models/dog.rb, db/migrate/20201119112526_add_confirmation_to_bookings.rb, db/migrate/20201119112649_add_hourly_rate_to_dogs.rb, db/schema.rb
@juagarca @jtdevuk @betharms 
Pull this if you want to work with the new dog and booking schema
=> booking and dog models adjusted with new columns

app/assets/stylesheets/components/_card_actions.scss, app/assets/stylesheets/components/_card_add_dog.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/users_controller.rb, app/views/shared/_add_dog_card.html.erb, app/views/shared/_card_show_profile.html.erb, app/views/shared/_profile_actions.html.erb, app/views/users/show.html.erb, db/schema.rb
@juagarca @odealtry @betharms 
Please review and merge
=> User profile front end

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/controllers/dogs_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js, app/javascript/plugins/init_mapbox.js, app/views/dogs/_info_window.html.erb, app/views/dogs/index.html.erb, app/views/dogs/show.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_card_show.html.erb, app/views/shared/_form.html.erb, app/views/shared/_form_dog_show.html.erb, app/views/users/edit.html.erb
Created the search functionality and the info card detail in the map 
@odealtry 
@jtdevuk @betharms
=> search function + map info cards

app/controllers/users_controller.rb, app/views/shared/_profile_actions.html.erb, app/views/shared/_user_show_booking_cards.html.erb
=> Profile bookings

app/views/shared/_user_show_booking_cards.html.erb
=> fixed booking photo bug

app/assets/stylesheets/components/_card-show.scss, app/assets/stylesheets/pages/_login.scss, app/controllers/dogs_controller.rb, app/views/bookings/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_card_show.html.erb, app/views/shared/_navbar.html.erb
also fixed the dimensions of the edit profile page
@odealtry @jtdevuk @betharms
=> fixed search, location and created payslips menu

app/assets/stylesheets/pages/_blog.scss, app/assets/stylesheets/pages/_index.scss, app/views/pages/blog.html.erb
=> blog fixed

app/controllers/dogs_controller.rb, app/views/dogs/index.html.erb
it was showing all the users even if they didn't have dogs when there was no params in the search so I fixed it
@jtdevuk
=> search fixed again

app/controllers/dogs_controller.rb, app/views/dogs/index.html.erb, app/views/dogs/show.html.erb
thanks guys! 
@odealtry @jtdevuk
=> doesn't show when user is the owner

app/assets/stylesheets/components/dog-show-box.scss, app/assets/stylesheets/pages/_dog-booking.scss, app/views/bookings/new.html.erb, app/views/users/show.html.erb
=> added h1 and reduced size of date fields

app/assets/stylesheets/pages/_profile.scss, app/javascript/components/confirm_buttons.js, app/javascript/packs/application.js, app/views/pages/blog.html.erb, app/views/shared/_user_show_lend_dog.html.erb
able to confirm bookings for demo
=> confirmed button js

app/controllers/users_controller.rb, app/views/shared/_user_show_hire_dog.html.erb, app/views/shared/_user_show_lend_dog.html.erb, app/views/users/show.html.erb
Fixed bugs with showing bookings @juagarca @odealtry @betharms
=> Confirmation on booking

Gemfile, config/initializers/unsplash.rb, db/schema.rb, db/seeds.rb
=> finally added photo to dogs
